### ISSUE TITLE
esbuild should be a CLI dependency

### ISSUE THREAD

**Issue by wKovacs64** [jacobparis-insiders/sly#17]
`esbuild` is required for `ts-loader.js` to compile TypeScript transformers, so it should be in `dependencies` (not `devDependencies` where it is now), right? It just so happens to work fine in Remix projects (the most likely place Sly is used today, I assume) because esbuild is already there, but when I was testing in an empty project, it threw an error because esbuild was not found.

**Comment by jacobparis** [comment]
Nice catch! This has been fixed and is available in one of the many new versions I created while trying to get CI to npm to work

**Comment by IHIutch** [comment]
Hm, I still appear to be having this issue using 1.7.0 and `pnpm`

**Comment by jacobparis** [comment]
> Hm, I still appear to be having this issue using 1.7.0 and `pnpm`

Sorry about this, somehow that commit didn't make it into the last release. Released in 1.8.0
